### ISSUE TITLE
Le forum à l'air légèrement hacké :D

### ISSUE THREAD

**Issue by valryon** [westindiecollective/westindiecollective.github.io#1]
L'URL du forum renvoie à une page bien louche.

**Comment by engleek** [comment]
Ahahahaha. Bien trouvé.

En fait, on a démantelé le serveur du forum puisque plus personne n'allait dessus (la preuve, ça fait des mois). Digitalocean a dû re-attribuer l'adresse IP, et maintenant la règle A du DNS que j'avais mis en place pour le sous-domaine pointe sur un site de… euh… de quelque chose.

**Comment by valryon** [comment]
"PFT est un expert dans la santé, fitness et bien-être"
ç'aurait été une drôle de reconversion du WIC 😀

**Comment by engleek** [comment]
Parfois faut pivoter vers des marchés plus propices. On pourrait proposer des services de santé pour le e-sport.
